### ISSUE TITLE
[Request] manhwa.club

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/extensions-madara#46] opened 2021-04-23 12:16 UTC
Link: https://manhwa.club/

**Comment by TheNetsky** [comment] 2021-04-24 08:00
Duplicate of #16

**Comment by AdrienSeon** [comment] 2021-04-24 09:57
Thanks for the request! 
Unfortunately, this source has already been asked before in #16

We will then close this one since it is a duplicate.

**Closed by AdrienSeon** 2021-04-24 09:57 UTC
Labels: duplicate
